name: Upload HTML to S3

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: deploy-thieslei
  BUCKET_FOLDER: htmlbuild


jobs:
  Upload_S3:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: AWS Access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Upload S3 Files
        run: aws s3 sync ./htmlbuild s3://${{ env.BUCKET_NAME }}/${{ env.BUCKET_FOLDER }} --acl public-read

